### PR TITLE
Read pagerIndicatorEnabled value each time a new page is selected

### PR DESCRIPTION
**Pull request by paolorotolo**
Please test and merge.

### CODE REVIEW

**Comment by avluis** [comment]
@paolorotolo I'm currently figuring this out - https://developer.android.com/studio/build/gradle-plugin-3-0-0-migration.html?utm_source=android-studio#variant_aware

**Comment by avluis** [comment]
@paolorotolo So due to some bugs (of course), I'm not able to test these changes until AppIntro implements flavors: https://issuetracker.google.com/issues/62170415#comment12

**Comment by paolorotolo** [comment]
Seems to be resolved in latest version. Are you using AS beta 2 and latest gradle version?

**Comment by avluis** [comment]
Yep -- I made sure I had the very latest (AS beta 2 and gradle 4.1) -- I can even build my test app when using AppIntro from JitPack, just not able to build from a local library.
Let me try pulling the branch from Jitpack and see if I'm able to get it to build from there as well.

**Comment by avluis** [comment]
@paolorotolo Using JitPack to build the branch works.

So the pager now updates when slides are changed but only then.
Pager indicator will show up on the first slide and when the screen is rotated (after changing the slide, which dismisses it).

I am calling `showPagerIndicator(false);` in `onCreate()`.
Note that my previous fix was to call this after a certain slide, but that's no longer a workaround.

**Comment by paolorotolo** [comment]
Yeah, my bad. I forgot to check the value on first start too. Try now.

**Comment by avluis** [comment]
Sorry for the wait -- I finally have some time on my hands and I just figured out how to pull the commit itself from JitPack so I'll be able to test every commit with no issue now.
I'll be back with a review soon.

**Pull request merged**
