### PR TITLE
Fixes permissions request behavior (Closes #471).

### LINKED ISSUE #471: Permissions request behavior is broken in latest release
From: https://github.com/apl-devs/AppIntro/commit/a6ff46b487f7607aafa8ec621526f83aefb55ee8#commitcomment-23369181

Before (`v4.2.0`):
* When navigating to the slide with a permission request, you would first see said slide (explaining what the permission was needed for) then you tap next and the permission request would be triggered.

After (`v4.2.1+`):
* When navigating to the slide with the permission request, the permission request is immediately triggered (as soon as you navigate to said slide).

### PR DESCRIPTION
**Pull request by paolorotolo**
Please test and merge.

### CODE REVIEW

**Comment by avluis** [comment]
On it -- give me a bit to attempt to reproduce on working code.

**Comment by avluis** [comment]
@paolorotolo
It's almost there -- the permission dialog is no longer triggering as soon as the permission slide is navigated to (good), but when you tap to navigate to the next slide it does so before showing the permission dialog (different behavior).

The above can be seen as a minor detail but it is different from prior behavior.
`v4.2.0` flow was:

- User navigates to slide tagged with a permission request (user reads what permissions the app will ask for).
- User taps next and a permission dialog will display (slide _does not_ change)
- User accepts/deny permission request (now we move to the next slide -- dev can choose to check onActivityResult() and take appropriate action)

**Comment by avluis** [comment]
@paolorotolo Would you be fine with that minor detail (slide changes first before showing permission dialog)?
I don't mind it but it is different from prior behavior.

**Comment by paolorotolo** [comment]
Okay, try now.
@avluis I also noticed there was a minor issue even in previous releases with permissions.
Slide changing (before release 4.2.0) was handled in ```onRequestPermissionsResult``` right after the permission was asked, manually changing the pager current item.

Now, this totally ignores the code defined by the user in ```onDonePressed``` or ```onNextPressed```. Now both issues should be fixed.

**Comment by avluis** [comment]
Got it -- pulling latest changes for testing~

**Comment by avluis** [comment]
@paolorotolo Note that you can remove an existing tag (`v4.2.2`) and release these changes with it (once said tag is reapplied on release).

**Comment by paolorotolo** [comment]
Awesome, I'll make another PR today and update AppIntro to SDK 26 (since DP3 with final API has been released this week) and then we can make a new release.

**Comment by avluis** [comment]
Neat! I take it there are no breaking changes with the new API?

**Comment by paolorotolo** [comment]
Or **Octopus** :))

**Comment by avluis** [comment]
I'm not sure I want that a condiment lol

**Comment by paolorotolo** [comment]
The Android Team is not sure either...

photo6037289830267857129

**Pull request merged**
