### PR TITLE
Feature/refactoring

### PR DESCRIPTION
**Pull request by TaniaSolo**
Removing code smells assignment.

### CODE REVIEW

**Comment by friederbluemle** [comment]
Note that the dependencies have already been updated to a more recent version in #413

**Comment by friederbluemle** [comment]
You should rebase your branch after #413 and remove the obsolete commits.

**Comment by paolorotolo** [comment]
Okay, we've merged #413. Can you please fix the conflicts and submit the pull again?
Thanks!

**Comment by avluis** [comment]
@paolorotolo Maybe we can ask for PRs to not touch dependencies as this just gets more troublesome when multiple PRs update said dependencies.
Basically, pull from master and work off that unless your PR requires that dependency (then the PR itself needs to note that).
What do you think?

**Comment by paolorotolo** [comment]
@avluis yeah, sounds good!

**Comment by paolorotolo** [comment]
Since this PR affects lots of code, I've manually solved the conflicts in build.gradle files. I'm merging this now to prevent other conflicts with future PRs.

Thanks!

**Pull request merged**
