### PR TITLE
Setup options to hide/show Seperator Bar  : void showSeparator(boolean showSeparator)

### PR DESCRIPTION
**Pull request by kaushikthedeveloper**
Static setting changer for changing visibility of Separator line in AppIntro slides (not for other layouts)

### CODE REVIEW

**Comment by kaushikthedeveloper** [comment]
Have only modified settings for bottom_separator in AppIntro as I did not want to makes changes to the UI for other layouts as of now (must see if we can find a workaround for the situation with other layouts).

Note : Simple modification of code for now, but which I thought was a necessary feature.

**Comment by kaushikthedeveloper** [comment]
@Andrew-Quebe please do review. This is my first Open Source contribution and am a tiny bit anxious of how it goes.

**Comment by avluis** [comment]
Quick tip:
Take a look at the code style that a project follows and adhere to it, e.g.;
- Do your if -> else condition statements contain braces?
- Are you respecting the usage of spaces (usually sets of 4) or tabs?
- When writing new methods, are you including documentation for anything that is not immediately clear?
- Are you taking care of not repeating yourself when making bigger edits to the codebase?

**Comment by kaushikthedeveloper** [comment]
@avluis , I am sure am following everything except putting braces for if-else condition. Thought for a single statement its is better without the braces. Will update that if required. And the changes made to the code are compact with proper documentation and does not affect anything else other than its intended target.

**Comment by paolorotolo** [comment]
LGTM, thanks!

**Pull request merged**
